name: 'Setup Node.js and Dependencies'
description: 'Checkout code, setup Node, and install dependencies'

runs:
  using: 'composite'
  steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: npm ci

